### ISSUE TITLE
Button mod-outline black/grey

### ISSUE THREAD

**Issue by almonais** [LuccaSA/lucca-front#1197]
```
.button.mod-outline {
  background-color: transparent;
  color: _color('grey');
  box-shadow: inset 0 0 0 1px _color('grey', '500');

  &:focus {
    box-shadow: inset 0 0 0 1px _color('primary');
    outline: none;
  }
}

.button.mod-outline:hover:not([disabled]),
.button.mod-outline:active {
  color: _color('grey', '800');
  background-color: transparent;
  box-shadow: inset 0 0 0 1px _color('grey', '800');
}
```

**Comment by lucienbertin** [comment]
i dont like this, the principle behind the palettes is that they are completely overridable so you cant really assume that a given palette exists

i'd rather you use the theme of the component for this
```scss
.button.mod-outline:active {
  // color: _color('grey', '800');
  color: _component('button.mod-outline.color');
  background-color: transparent;
  // box-shadow: inset 0 0 0 1px _color('grey', '800');
  box-shadow: inset 0 0 0 1px _component('button.mod-outline.border-color');
}
```

even if in the default theme of the button you use the `_color('grey', '800')` to define the value of `_component('button.mod-outline.color');` or `_component('button.mod-outline.border-color');`
