### ISSUE TITLE
New "format corner" icons

### ISSUE THREAD

**Issue by shajz** [LuccaSA/lucca-front#2342]
These rotated versions of `icon-formatCornerUpLeft` and `icon-formatCornerUpRight` are not available in LF

![image](https://github.com/LuccaSA/lucca-front/assets/2089620/84a69934-1b0c-4321-8a77-2ac1c0920136)
Figma link : https://www.figma.com/file/alAvrHFhbx4BVIHkIeb6oH/Export-comptable---Admin---Achats?type=design&node-id=4396-172850&mode=design&t=kWUmWlMmMpgNnfwe-4

I get by for now with this bit of scss (in a dropdown), but it would be nice to have them available

```scss
.lu-dropdown-options-item-action {
  .lucca-icon.icon-formatCornerUpLeft {
    transform: rotate(90deg);
  }
  .lucca-icon.icon-formatCornerUpRight {
    transform: rotate(90deg);
  }
}

```
