### ISSUE TITLE
[Grid] Auto and Responsive 

### ISSUE THREAD

**Issue by jeremie-lucca** [LuccaSA/lucca-front#2478]
To discuss @vvalentin-lucca 

We should provide an option with `.grid.mod-auto` to toggle on full line cells on a specific breakpoint.

![image](https://github.com/LuccaSA/lucca-front/assets/25581936/dd2ce361-8587-4aee-9749-9f0ec101b3d5)

A second feedback from Yoan pointed out that we now have to set an additional `--grid-colspan` on each column to have full line cells on small resolutions. We might need to have generic responsive classes to switch on full line cells on a specific breakpoint (something like `.mod-fullWidth-M` to apply on `.grid`). 

Last point: 
The position responsive documentation is missed by UI devs. I suggest to remove the generic responsive story and add extra responsive documentation in each contexts (fusion, position, etc.)

**Comment by vvalentin-lucca** [comment]
For `mod-auto` management, wouldn't a bit of CSS like this be enough?

```scss
@use '@lucca-front/scss/src/components/grid/exports' as grid;

.myCustomGrid {
  --grid-columns: 1;

  @include media.min(M) {
    @include grid.auto;
  }
}

```
