### ISSUE TITLE
[Empty State] Content overflows the viewports on narrow viewports

### ISSUE THREAD

**Issue by fbasmaison-lucca** [LuccaSA/lucca-front#2815]
When viewed on narrow viewports, the content will be minimum `calc(25rem + var(--spacings-XXS) * 2)` wide.

Could a `clamp` or a `min-width` with variables be used?

The properties at the top of the screenshot below illustrate the issue.

<img width="1097" alt="image" src="https://github.com/LuccaSA/lucca-front/assets/144820795/cf35941c-6d86-45f2-b828-305455a8773a">

**Comment by fbasmaison-lucca** [comment]
Cleaning Empty States, I can’t reproduce this bug anymore, but I also did not find where the change happened.

Reopen if appropriate.

**Comment by fbasmaison-lucca** [comment]
Found another case where the content does overflow.

Possible mitigation in the shame:

```scss
.emptyState-content {
  width: clamp(0%, calc(var(--components-emptyState-idealWidth, 25rem) + var(--pr-t-spacings-50) * 2), 100%) !important;
}
```
