### ISSUE TITLE
[Timeline] Get information of "already completed" steps

### ISSUE THREAD

**Issue by Nurovek** [LuccaSA/lucca-front#3001]
On the timeline component, it's possible to go back (and forward) to already completed steps. 

However, there is no visual indication of which future steps are already completed and successful (they are greyed-out). 

We need a 'checked' or 'step-completed' state for future steps to avoid mistakenly thinking that the step is not yet completed (greyed out). 

Past steps are correctly indicated as checked.

**Current:**
![image](https://github.com/user-attachments/assets/72294dde-5215-434d-b2ae-aad5e4d4db7e)
(Steps 3 & 4 are actually completed thus clickable)

**Expected:**
![image (14)](https://github.com/user-attachments/assets/99eb9ffe-264a-4b59-8446-1a8050206369)

**Comment by lmullot** [comment]
I have a similar needs that doesn't include that the step is past or futur, I juste want that all "valid" step are checked and others stay as default.

```html
<ol class="timeline mod-number mod-L mod-checkedValidStep">
  @for (step of steps; track step) {
    @let isActiveStep = store.activeStep() === step;
    <li class="timeline-step" [attr.aria-current]="isActiveStep ? 'step' : undefined" [class.is-valid]="step | ptIsValidStep">
        ....
    </li>
  }
</ol>

```

```scss
.timeline {
  &.mod-checkedValidStep {
    // Default state, not selected, not valid
    .timeline-step {
      .timeline-step-title {
        color: var(--palettes-neutral-600);

        &::before {
          background-color: var(--palettes-neutral-200);
          color: var(--palettes-neutral-600);
        }

        .timeline-step-title-icon {
          &::before {
            background-color: transparent;
          }
        }
      }
    }

    // Selected state
    .timeline-step:is([aria-current='step']) {
      .timeline-step-title {
        color: var(--palettes-product-800);

        &::before {
          background-color: var(--palettes-product-800);
          color: var(--colors-white-color);
        }
      }
    }

    // Timeline step separator
    .timeline-step:not([aria-current='step']):not(
        [aria-current='step'] ~ .timeline-step
      ):not(.timeline-stepAddBetweenStep)::after {
      border-color: var(--palettes-200, var(--palettes-product-200));
      border-bottom-style: solid;
    }

    // Valid state
    .timeline-step:not([aria-current='step']) {
      &.is-valid {
        .timeline-step-title {
          color: var(--palettes-product-800);

          &::before {
            background-color: var(--palettes-product-300) !important;
            color: var(--palettes-700, var(--palettes-product-700));
          }

          .timeline-step-title-icon {
            &::before {
              left: 7px !important;
              color: var(--palettes-neutral-700) !important;
              font-weight: bold !important;
            }
          }
        }
      }
    }
  }
}
```
