### ISSUE TITLE
[indexTable] Class`mod-layoutFixedAtMediaMin#{$breakpoint}`can't be efficient

### ISSUE THREAD

**Issue by Juliecottu** [LuccaSA/lucca-front#3226]
In the component IndexTable, the following rule overrides the media query introduced by `AtMediaMin#{$breakpoint}`: 

In `scss/src/components/indexTable/index.scss`
```css
.indexTable {
[...]
    &[class*='mod-layoutFixed'] {
    	@include layoutFixed; // => /scss/src/components/indexTable/mods.scss
    }
[...]
  }
```

and in `/scss/src/components/indexTable/mods.scss`
```css
@mixin layoutFixed {
	table-layout: fixed;
[...]
}
```
