### ISSUE TITLE
No action in Empty State creates added spacing

### ISSUE THREAD

**Issue by fbasmaison-lucca** [LuccaSA/lucca-front#3296]
An Empty State with no actions creates the container for the potential buttons (`emptyState-actions`).

Shall we not have `emptyState-actions` when an Empty State contains no action or is the current behaviour on purpose?

A _shame.scss_ alternative can be to hide `emptyState-actions`:

```css
.emptyState-actions:empty {
  display: none;
}
```

![Image](https://github.com/user-attachments/assets/aa15a58d-1f7f-4a38-9075-fb18be872aa7)
