### ISSUE TITLE
[tableSortable] mod-withIcon on the button

### ISSUE THREAD

**Issue by fbasmaison-lucca** [LuccaSA/lucca-front#3453]
When using `lu-icon` within a `tableSortable` sub-component, a `mod-withIcon` class is added to the button, which adds an unwanted padding.

The shame file of Business Expenses will have the following:

```scss
@use '@lucca-front/scss/src/commons/utils/media';

.button.tableSortable {
  @include media.min('S') {
    max-width: 100%; // Unrelated to the current issue

    &.mod-withIcon {
      --components-button-padding: 0 var(--pr-t-spacings-50);
    }
  }
}
```

— [Source of the conversation on Slack](https://lucca.slack.com/archives/C3W78FWUU/p1740398723345079)
